import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "How does Chat Gig work with ChatGPT?",
    answer:
      "Chat Gig integrates seamlessly with ChatGPT through a plugin/extension. As you have a natural conversation about your project, Chat Gig analyzes the discussion and automatically generates a structured brief that captures all the important details.",
  },
  {
    question: "Do I need to change how I use ChatGPT?",
    answer:
      "Not at all! Just chat naturally about your project ideas, requirements, or goals. Chat Gig works in the background to understand and structure your conversation without interrupting your workflow.",
  },
  {
    question: "Can I edit the generated briefs?",
    answer:
      "Absolutely. Every brief generated by Chat Gig is fully editable. You can review, modify, and refine the content before sharing it with freelancers to ensure it perfectly matches your needs.",
  },
  {
    question: "What types of projects does Chat Gig support?",
    answer:
      "Chat Gig supports a wide range of projects including software development, web design, graphic design, content writing, marketing, and more. Our AI adapts to different project types and industries.",
  },
  {
    question: "Is there a free trial?",
    answer:
      "We're currently in beta and building our waitlist. Early users will get exclusive access and special pricing when we launch. Join the waitlist to be notified when we're ready!",
  },
  {
    question: "How is Chat Gig different from other freelancer platforms?",
    answer:
      "Chat Gig isn't a freelancer platform - it's a tool that helps you create better project briefs. You can use the generated briefs on any platform like Fiverr, Upwork, or Freelancer. We focus on making the brief creation process effortless.",
  },
];

export function FAQ() {
  return (
    <section id="faq" className="py-24 bg-white">
      <div className="mx-auto max-w-4xl px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold tracking-tight text-[var(--color-text-heading)] sm:text-4xl mb-4">
            Frequently asked questions
          </h2>
          <p className="text-lg text-[var(--color-text-muted)]">
            Everything you need to know about Chat Gig
          </p>
        </div>

        {/* FAQ Accordion */}
        <Accordion type="single" collapsible className="w-full space-y-4">
          {faqs.map((faq, index) => (
            <AccordionItem
              key={index}
              value={`item-${index}`}
              className="border border-gray-200 rounded-lg px-6 bg-white shadow-sm hover:shadow-md transition-shadow"
            >
              <AccordionTrigger className="text-left text-lg font-semibold text-[var(--color-text-heading)] hover:text-[var(--color-ghostteam-green)] hover:no-underline py-5">
                {faq.question}
              </AccordionTrigger>
              <AccordionContent className="text-[var(--color-text-muted)] leading-relaxed pb-5">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
